package com.pdf.pdfreader.pdfviewer.editor.common

enum class FunctionState {
    CONTINUOUS_PAGE, PAGE_BY_PAGE, NIGHT_MODE, GO_PAGE, FAVORITE, RENAME, PRINT, DELETE, BROWSE_FILE,
    RATE_US, FEEDBACK, SHARE_APP, PRIVACY_POLICY, CHANGE_LANGUAGE, CLEAR_RECENT, CLEAR_FAVORITE, SHARE,
    RECENT, DETAIL, CREATE_SHORTCUT
}